# Generated by Django 2.2.7 on 2020-01-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='app',
            field=models.BooleanField(default=False),
        ),
    ]
