# Generated by Django 2.2.7 on 2020-02-16 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_app'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='app',
        ),
    ]
